### ISSUE TITLE
ETA?

### ISSUE THREAD

**Issue by deviousasti** [cloudlayerio/cloudlayerio-fsharp#1]
Pleasantly surprised to see an F# library project, rather than a wrapper around a C# API.

**Comment by elucidsoft** [comment]
Yes, in fact, I am looking and paying for volunteers to help contribute and maintain this project with a couple goals.

1. I want to give junior developers the opportunity to contribute to something using F#.
2. I want to sponsor or fund them to contribute to the project.
3. I want to help them grow their career and help them advance themselves in the open-source community.

I specifically didn't want to generate a cheap wrapper or an auto-generated Swagger Library as I think those are not interesting or nearly as good.  I could write this myself, but I am trying this strategy first.  Again, I will GitHub sponsor or pay outright for a time as an additional incentive for someone interested.

I am also doing the following projects:

- cloudlayer-net (c#)
- cloudlayer-php
- cloudlayer-go
- cloudlayer-rust
- cloudlayer-nodejs (Typescript)
- cloudlayer-cli (this will most likely be done in Go)

**Comment by deviousasti** [comment]
I was looking around for a URL screenshot service for a project, and this is probably the most economical I could find by far.
I like the idea - I wish there was something like this when I was getting started with OSS.

.Net 5 has single file deployment, so the CLI could be done in it as well.
The API surface seems small enough. 

An interesting detail will be how to run tests.
